Update commands-queue.ts
NodeRedis/node-redis pull request #1630
Opened 2021-07-17 21:26 UTC by NovaAtWarren

Hopefully fixes #1628

### Description

Fixes using string length instead of byte length when encoding command
### Checklist

- [ ] Does `npm test` pass with this change (including linting)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

2021-07-17 21:47 UTC, NovaAtWarren commented
Just got my laptop on, did some testing with `\u{1f91e}`, and it seems it's already picking it up as 2 bytes with the old method.
As I've already written the test I'll leave this open, but I'll revert 2fa5ef6.

2021-07-18 03:05 UTC, MCPE-PC requested changes
str.length is UTF-16 characters count

## Check 1.

![Runkit](https://user-images.githubusercontent.com/20432839/126054190-72def26d-5c7a-4b00-8d70-34ba71b01231.png)

 - `'\u{1f91e}'.length !== Buffer.byteLength('\u{1f91e}');`
 - `본` is 3 bytes, `'본'.length` is 1

## Check 2.

![UnicodePad](https://user-images.githubusercontent.com/20432839/126054188-618e3e63-3fc5-4ee7-b4a5-1dd18971261c.png)

U+1F91E is an emoji and is 4 bytes

2021-07-18 08:49 UTC, NovaAtWarren commented
@MCPE-PC I've changed back to `Buffer.byteLength()`, and set the tests to look for a bytecount of 4, but it's now failing the test on my machine:
```#  1) Command Queue
       UTF-16 Byte length check (see #1628):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '*1\r\n$2\r\n🤞\r\n'
- '*1\r\n$4\r\n🤞\r\n'
          ^
```
I'm not quite sure yet, but it seems as if the different machines might be using different encoding standards (e.g `utf-8` and `utf-16`)
Not sure how much time I'll have today, but I'll look into this further.
Sorry for dismissing you earlier.

2021-07-18 09:15 UTC, NovaAtWarren commented
Turns out there were two places that calculated the length of a string
https://github.com/NodeRedis/node-redis/blob/c72aab2fc29a9cc994f6b810aeb10a4fe1863f29/lib/commands-queue.ts#L47
and
https://github.com/NodeRedis/node-redis/blob/c72aab2fc29a9cc994f6b810aeb10a4fe1863f29/lib/commands-queue.ts#L53

The fix you wrote worked perfectly fine, I just didn't encounter it because I put the special character in the wrong place to encounter the specific issue you did.

Thank you for the help, re-opening PR for review and merging.

2021-07-18 10:42 UTC, MCPE-PC approved these changes

2021-07-18 10:42 UTC, MCPE-PC commented on lib/commands-queue.ts
>              const str = args[i].toString();
```suggestion
```
As `args` is `string[]`, this line also seems to need to be reviewed. Is it casting `string` to a `string`?

2021-07-20 17:13 UTC, leibale approved these changes

2021-07-20 17:16 UTC, merged

2021-07-20 17:16 UTC, leibale commented
@NovaAtWarren @MCPE-PC thank you very much! :)